# Generated by Django 5.0.4 on 2024-07-05 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Hebergement', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artisanat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hebergement.localisation')),
                ('responsable_artisanat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aoio', to='Accounts.responsableetablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artisanal.panier')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Livré', 'Livré'), ('Annulé', 'Annulé')], default='En attente', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
                ('panier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Artisanal.panier')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitArtisanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_artisanat', models.TextField()),
                ('prix_artisanat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible_artisanat', models.BooleanField(default=True)),
                ('image_artisanat', models.ImageField(blank=True, upload_to='artisanat_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='Artisanal.artisanat')),
            ],
        ),
        migrations.AddField(
            model_name='panier',
            name='produits',
            field=models.ManyToManyField(through='Artisanal.ItemPanier', to='Artisanal.produitartisanal'),
        ),
        migrations.AddField(
            model_name='itempanier',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artisanal.produitartisanal'),
        ),
    ]
