# Generated by Django 5.0.4 on 2024-07-04 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_responsableetablissement_options'),
        ('Artisanal', '0001_initial'),
        ('Hebergement', '0002_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artisanat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hebergement.localisation')),
                ('responsable_artisanat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuck', to='Accounts.responsableetablissement')),
            ],
        ),
    ]
