# Generated by Django 5.0.4 on 2024-07-03 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisanal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
        migrations.CreateModel(
            name='ItemPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artisanal.produitartisanal')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to=settings.AUTH_USER_MODEL)),
                ('produits', models.ManyToManyField(through='Artisanal.ItemPanier', to='Artisanal.produitartisanal')),
            ],
        ),
        migrations.AddField(
            model_name='itempanier',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artisanal.panier'),
        ),
        migrations.AddField(
            model_name='commande',
            name='panier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Artisanal.panier'),
        ),
    ]
