# Generated by Django 5.0.4 on 2024-07-04 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_responsableetablissement_options'),
        ('Artisanal', '0002_artisanat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanat',
            name='responsable_artisanat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aoio', to='Accounts.responsableetablissement'),
        ),
    ]
