# Generated by Django 5.0.4 on 2024-07-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artisanal', '0002_remove_commande_produit_remove_commande_quantite_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livraison',
        ),
    ]
