# Generated by Django 5.0.4 on 2024-07-04 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisanal', '0003_alter_artisanat_responsable_artisanat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitartisanal',
            name='responsable_artisanat',
        ),
        migrations.AddField(
            model_name='produitartisanal',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='Artisanal.artisanat'),
        ),
    ]
