# Generated by Django 5.0.6 on 2024-07-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_admin', models.CharField(max_length=100)),
                ('prenom_admin', models.CharField(max_length=100)),
                ('email_admin', models.EmailField(max_length=254)),
                ('mdp_admin', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
