# Generated by Django 5.0.6 on 2024-07-02 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_hotel', models.CharField(max_length=100)),
                ('description_hotel', models.TextField()),
                ('addresse_hotel', models.CharField(max_length=200)),
                ('ville_hotel', models.CharField(max_length=100)),
                ('nombre_etoile_hotel', models.IntegerField()),
                ('latitude_hotel', models.FloatField()),
                ('longitude_hotel', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hotel', models.ImageField(upload_to='hotel_images')),
                ('legende_hotel', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Administrateurs.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_responsable', models.EmailField(max_length=254)),
                ('nom_responsable', models.CharField(max_length=100)),
                ('prenom_responsable', models.CharField(max_length=100)),
                ('mdp_responsable', models.CharField(max_length=100)),
                ('numero_responsable', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Administrateur',
        ),
        migrations.AddField(
            model_name='hotel',
            name='responsable_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='Administrateurs.responsable_etablissement'),
        ),
    ]
