# Generated by Django 5.0.6 on 2024-07-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateurs', '0002_hotel_hotelimage_responsable_etablissement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image_hotel',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_image'),
        ),
    ]
