# Generated by Django 5.0.6 on 2024-07-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateurs', '0003_hotel_image_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelimage',
            old_name='image_hotel',
            new_name='images',
        ),
    ]
