# Generated by Django 5.0.6 on 2024-07-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateurs', '0005_remove_hotelimage_hotel_hebergement_hebergementimage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Responsable_etablissement',
            new_name='ResponsableEtablissement',
        ),
    ]
