# Generated by Django 5.0.6 on 2024-07-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateurs', '0006_rename_responsable_etablissement_responsableetablissement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hebergement',
            name='image_hebergement',
        ),
        migrations.AddField(
            model_name='hebergementimage',
            name='couverture',
            field=models.BooleanField(default=False),
        ),
    ]
