# Generated by Django 5.0.6 on 2024-07-03 09:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateurs', '0007_remove_hebergement_image_hebergement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='responsableetablissement',
            name='numero_responsable',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro doit commencer par 032, 033, 034 ou 038 et contenir 7 chiffres supplémentaires.', regex='^(032|033|034|038)\\d{7}$')]),
        ),
        migrations.AddField(
            model_name='responsableetablissement',
            name='type_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Administrateurs.typeresponsable'),
        ),
    ]
