# Generated by Django 5.0.4 on 2024-07-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResponsableEtablissement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Responsable_etablissement',
        ),
    ]
