# Generated by Django 5.0.4 on 2024-07-03 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeArtisanat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commande', models.IntegerField()),
                ('prix_total_commande', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_validee_commande', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
                ('responsable_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='Accounts.responsableetablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_hotel', models.CharField(max_length=100)),
                ('description_hotel', models.TextField()),
                ('addresse_hotel', models.CharField(max_length=200)),
                ('ville_hotel', models.CharField(max_length=100)),
                ('nombre_etoile_hotel', models.IntegerField()),
                ('latitude_hotel', models.FloatField()),
                ('longitude_hotel', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('responsable_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='Accounts.responsableetablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_chambre', models.CharField(max_length=100)),
                ('prix_nuit_chambre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible_chambre', models.BooleanField(default=True)),
                ('nombre_personnes', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='BDD.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_accessoire', models.CharField(max_length=100)),
                ('description_accessoire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_accessoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessoires', to='BDD.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hotel', models.ImageField(upload_to='hotel_images')),
                ('legende_hotel', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='BDD.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='Accounts.responsableetablissement')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitArtisanals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_artisanat', models.CharField(max_length=100)),
                ('description_artisanat', models.TextField()),
                ('prix_artisanat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible_artisanat', models.BooleanField(default=True)),
                ('image_artisanat', models.ImageField(blank=True, upload_to='artisanat_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable_artisanat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_artisanat', to='Accounts.responsableetablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_reserve', models.DateField()),
                ('date_fin_reserve', models.DateField()),
                ('nombre_personnes_reserve', models.IntegerField(default=1)),
                ('prix_total_reserve', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_validee_reserve', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chambre_reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='BDD.chambre')),
                ('client_reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('hotel_reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='BDD.hotel')),
            ],
        ),
    ]
