# Generated by Django 5.0.6 on 2024-07-01 23:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_admin', models.CharField(max_length=100)),
                ('prenom_admin', models.CharField(max_length=100)),
                ('email_admin', models.EmailField(max_length=254)),
                ('mdp_admin', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('prenom_client', models.CharField(max_length=100)),
                ('email_client', models.EmailField(max_length=254)),
                ('numero_client', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro doit commencer par 032, 033, 034 ou 038 et contenir 7 chiffres supplémentaires.', regex='^(032|033|034|038)\\d{7}$')])),
                ('mdp_client', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_hotel', models.CharField(max_length=100)),
                ('description_hotel', models.TextField()),
                ('addresse_hotel', models.CharField(max_length=200)),
                ('ville_hotel', models.CharField(max_length=100)),
                ('nombre_etoile_hotel', models.IntegerField()),
                ('latitude_hotel', models.FloatField()),
                ('longitude_hotel', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_responsable', models.EmailField(max_length=254)),
                ('nom_responsable', models.CharField(max_length=100)),
                ('prenom_responsable', models.CharField(max_length=100)),
                ('mdp_responsable', models.CharField(max_length=100)),
                ('numero_responsable', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro doit commencer par 032, 033, 034 ou 038 et contenir 7 chiffres supplémentaires.', regex='^(032|033|034|038)\\d{7}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_chambre', models.CharField(max_length=100)),
                ('prix_nuit_chambre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible_chambre', models.BooleanField(default=True)),
                ('nombre_personnes', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='BDD.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_accessoire', models.CharField(max_length=100)),
                ('description_accessoire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_accessoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessoires', to='BDD.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hotel', models.ImageField(upload_to='hotel_images')),
                ('legende_hotel', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='BDD.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_reserve', models.DateField()),
                ('date_fin_reserve', models.DateField()),
                ('nombre_personnes_reserve', models.IntegerField(default=1)),
                ('prix_total_reserve', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_validee_reserve', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chambre_reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='BDD.chambre')),
                ('client_reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='BDD.client')),
                ('hotel_reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='BDD.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='BDD.client')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='BDD.responsable_etablissement')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='responsable_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='BDD.responsable_etablissement'),
        ),
        migrations.CreateModel(
            name='CommandeArtisanat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commande', models.IntegerField()),
                ('prix_total_commande', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_validee_commande', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='BDD.client')),
                ('responsable_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='BDD.responsable_etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Artisanat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_artisanat', models.CharField(max_length=100)),
                ('description_artisanat', models.TextField()),
                ('prix_artisanat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible_artisanat', models.BooleanField(default=True)),
                ('image_artisanat', models.ImageField(blank=True, upload_to='artisanat_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable_artisanat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_artisanat', to='BDD.responsable_etablissement')),
            ],
        ),
    ]
