# Generated by Django 5.0.4 on 2024-07-02 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('BDD', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrateur',
        ),
        migrations.AlterField(
            model_name='message',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='Accounts.client'),
        ),
        migrations.AlterField(
            model_name='commandeartisanat',
            name='client_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='Accounts.client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client_reserve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Accounts.client'),
        ),
        migrations.AlterField(
            model_name='artisanat',
            name='responsable_artisanat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_artisanat', to='Accounts.responsable_etablissement'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='responsable_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='Accounts.responsable_etablissement'),
        ),
        migrations.AlterField(
            model_name='commandeartisanat',
            name='responsable_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='Accounts.responsable_etablissement'),
        ),
        migrations.AlterField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='Accounts.responsable_etablissement'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Responsable_etablissement',
        ),
    ]
