# Generated by Django 5.0.4 on 2024-07-03 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateurs', '0001_initial'),
        ('BDD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='responsable_hotel',
        ),
        migrations.AlterField(
            model_name='chambre',
            name='hotel_chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='Administrateurs.hebergement'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hotel_reserve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Administrateurs.hebergement'),
        ),
        migrations.AlterField(
            model_name='accessoire',
            name='hotel_accessoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessoires', to='Administrateurs.hebergement'),
        ),
        migrations.DeleteModel(
            name='HotelImage',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
