# Generated by Django 5.0.4 on 2024-07-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0003_rename_artisanat_produitartisanals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
