# Generated by Django 5.0.4 on 2024-07-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typecartebancaire',
            name='regex_pattern',
            field=models.CharField(default='^$', help_text='Expression régulière pour la validation du numéro de carte bancaire', max_length=255),
        ),
    ]
