# Generated by Django 5.0.4 on 2024-07-04 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsableetablissement',
            options={'verbose_name': 'ResponsableEtablissement', 'verbose_name_plural': 'ResponsableEtablissement'},
        ),
    ]
