# Generated by Django 5.0.4 on 2024-07-02 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('BDD', '0002_delete_administrateur_alter_message_destinataire_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Responsable_etablissement',
            new_name='ResponsableEtablissement',
        ),
    ]
