# Generated by Django 5.0.4 on 2024-07-02 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_responsable_etablissement_responsableetablissement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='responsableetablissement',
            name='type_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.typeresponsable'),
        ),
    ]
