# Generated by Django 5.0.4 on 2024-07-03 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_client_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsableetablissement',
            old_name='mdp_responsable',
            new_name='password_responsable',
        ),
    ]
