# Generated by Django 5.0.4 on 2024-07-05 08:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourOperateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_operateur', models.CharField(max_length=100)),
                ('adresse_operateur', models.CharField(max_length=255)),
                ('email_operateur', models.EmailField(max_length=254, unique=True)),
                ('telephone_operateur', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro doit commencer par 032, 033, 034 ou 038 et contenir 7 chiffres supplémentaires.', regex='^(032|033|034|038)\\d{7}$')])),
                ('description_operateur', models.TextField(blank=True, null=True)),
                ('image_tour', models.ImageField(blank=True, null=True, upload_to='images/Tour_operateur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable_TourOperateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourOperateur', to='Accounts.responsableetablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_voyage', models.CharField(max_length=100)),
                ('description_voyage', models.TextField()),
                ('destination_voyage', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('prix_voyage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('places_disponibles', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour_operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='TourOperateur.touroperateur')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation_voyage', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmée'), ('pending', 'En attente'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='TourOperateur.voyage')),
            ],
        ),
        migrations.CreateModel(
            name='ImageVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/Touroperateur_voyage')),
                ('description', models.TextField(blank=True, null=True)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='TourOperateur.voyage')),
            ],
        ),
    ]
