# Generated by Django 5.0.4 on 2024-07-03 15:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0002_typecartebancaire_regex_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourOperateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_operateur', models.CharField(max_length=100)),
                ('adresse_operateur', models.CharField(max_length=255)),
                ('email_operateur', models.EmailField(max_length=254, unique=True)),
                ('telephone_operateur', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro doit commencer par 032, 033, 034 ou 038 et contenir 7 chiffres supplémentaires.', regex='^(032|033|034|038)\\d{7}$')])),
                ('description_operateur', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable_TourOperateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourOperateur', to='Accounts.responsableetablissement')),
            ],
        ),
    ]
