# Generated by Django 5.0.4 on 2024-07-03 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourOperateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_voyage', models.CharField(max_length=100)),
                ('description_voyage', models.TextField()),
                ('destination_voyage', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('prix_voyage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('places_disponibles', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour_operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='TourOperateur.touroperateur')),
            ],
        ),
    ]
