# Generated by Django 5.0.4 on 2024-07-03 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourOperateur', '0002_voyage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='TourOperateur.voyage')),
            ],
        ),
    ]
