# Generated by Django 5.0.4 on 2024-07-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourOperateur', '0004_reservation_voyage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagevoyage',
            name='image',
            field=models.ImageField(upload_to='images/voyage_chambre'),
        ),
    ]
