# Generated by Django 5.0.4 on 2024-07-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourOperateur', '0005_alter_imagevoyage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='touroperateur',
            name='image_tour',
            field=models.ImageField(blank=True, null=True, upload_to='images/Tour_operateur'),
        ),
        migrations.AlterField(
            model_name='imagevoyage',
            name='image',
            field=models.ImageField(upload_to='images/voyage'),
        ),
    ]
