# Generated by Django 5.0.4 on 2024-07-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourOperateur', '0006_touroperateur_image_tour_alter_imagevoyage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagevoyage',
            name='image',
            field=models.ImageField(upload_to='images/Touroperateur_voyage'),
        ),
    ]
