# Generated by Django 5.0.4 on 2024-07-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
