# Generated by Django 5.0.4 on 2024-07-03 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0002_rename_typeresponsable_typehebergement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebergement',
            name='type_hebergement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hebergement.typehebergement'),
        ),
    ]
