# Generated by Django 5.0.4 on 2024-07-03 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0004_accessoire_chambre_message_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoire',
            name='hotel_accessoire',
        ),
        migrations.CreateModel(
            name='HebergementAccessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hebergement.accessoire')),
                ('hebergement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hebergement.hebergement')),
            ],
        ),
        migrations.AddField(
            model_name='hebergement',
            name='accessoires',
            field=models.ManyToManyField(through='Hebergement.HebergementAccessoire', to='Hebergement.accessoire'),
        ),
    ]
