# Generated by Django 5.0.4 on 2024-07-03 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0006_accessoirehotel_rename_accessoire_accessoirechambre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChambrePersonaliser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_chambre', models.CharField(max_length=100)),
                ('nombre_personnes', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='disponible_chambre',
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='hotel_chambre',
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='prix_nuit_chambre',
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='HebergementChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_nuit_chambre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible_chambre', models.BooleanField(default=True)),
                ('accessoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hebergement.accessoirechambre')),
                ('chambre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hebergement.chambre')),
                ('chambre_personaliser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hebergement.chambrepersonaliser')),
                ('hebergement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hebergement.hebergement')),
            ],
        ),
        migrations.CreateModel(
            name='ImageChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images_chambre')),
                ('couverture', models.BooleanField(default=False)),
                ('legende_chambre', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hebergement_chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_chambre', to='Hebergement.hebergementchambre')),
            ],
        ),
    ]
