# Generated by Django 5.0.4 on 2024-07-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0007_chambrepersonaliser_remove_chambre_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessoireHotel',
            new_name='AccessoireHebergement',
        ),
    ]
