# Generated by Django 5.0.4 on 2024-07-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0008_rename_accessoirehotel_accessoirehebergement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chambre',
            old_name='nombre_personnes',
            new_name='nombre_max_personnes',
        ),
        migrations.AddField(
            model_name='chambre',
            name='nombre_min_personnes',
            field=models.IntegerField(default=1),
        ),
    ]
