# Generated by Django 5.0.4 on 2024-07-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0009_rename_nombre_personnes_chambre_nombre_max_personnes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebergementimage',
            name='images',
            field=models.ImageField(upload_to='image/hebergement_images'),
        ),
        migrations.AlterField(
            model_name='imagechambre',
            name='images',
            field=models.ImageField(upload_to='image/images_chambre'),
        ),
    ]
