# Generated by Django 5.0.4 on 2024-07-03 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0010_alter_hebergementimage_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hebergementchambre',
            name='accessoire',
        ),
        migrations.CreateModel(
            name='HebergementChambreAccessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('accessoire_chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hebergement.accessoirechambre')),
                ('hebergement_chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hebergement.hebergementchambre')),
            ],
        ),
        migrations.AddField(
            model_name='hebergementchambre',
            name='accessoires',
            field=models.ManyToManyField(through='Hebergement.HebergementChambreAccessoire', to='Hebergement.accessoirechambre'),
        ),
    ]
