# Generated by Django 5.0.4 on 2024-07-03 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0011_remove_hebergementchambre_accessoire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebergementchambre',
            name='chambre_personaliser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hebergement.chambrepersonaliser'),
        ),
    ]
