# Generated by Django 5.0.4 on 2024-07-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0012_alter_hebergementchambre_chambre_personaliser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebergementimage',
            name='images',
            field=models.ImageField(upload_to='images/hebergement_images'),
        ),
        migrations.AlterField(
            model_name='imagechambre',
            name='images',
            field=models.ImageField(upload_to='images/images_chambre'),
        ),
    ]
