# Generated by Django 5.0.4 on 2024-07-03 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0013_alter_hebergementimage_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebergementchambre',
            name='chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hebergement.chambre'),
        ),
    ]
