# Generated by Django 5.0.4 on 2024-07-03 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0014_alter_hebergementchambre_chambre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hebergement',
            name='adresse_hebergement',
        ),
        migrations.RemoveField(
            model_name='hebergement',
            name='latitude_hebergement',
        ),
        migrations.RemoveField(
            model_name='hebergement',
            name='longitude_hebergement',
        ),
        migrations.RemoveField(
            model_name='hebergement',
            name='ville_hebergement',
        ),
        migrations.AddField(
            model_name='hebergement',
            name='localisation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hebergement', to='Hebergement.localisation'),
        ),
    ]
