# Generated by Django 5.0.4 on 2024-07-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0015_localisation_remove_hebergement_adresse_hebergement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hebergementimage',
            name='images',
        ),
    ]
