# Generated by Django 5.0.4 on 2024-07-05 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0016_remove_hebergementimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='chambre_reserve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Hebergement.hebergementchambre'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
