# Generated by Django 5.0.4 on 2024-07-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0017_alter_reservation_chambre_reserve_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebergementchambre',
            name='disponible_chambre',
            field=models.IntegerField(null=True),
        ),
    ]
