# Generated by Django 5.0.4 on 2024-07-05 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0018_alter_hebergementchambre_disponible_chambre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hebergement',
            name='localisation',
        ),
        migrations.AddField(
            model_name='localisation',
            name='hebergement_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hebergement', to='Hebergement.hebergement'),
        ),
    ]
